package io.github.tabilzad.ktor.k2

import io.github.tabilzad.ktor.OpenApiSpecCollector
import io.github.tabilzad.ktor.PluginConfiguration
import io.github.tabilzad.ktor.model.PartialSpecLocation
import io.github.tabilzad.ktor.output.OpenApiSpec
import io.github.tabilzad.ktor.output.PartialOpenApiSpec
import io.github.tabilzad.ktor.output.PartialSpecs
import io.github.tabilzad.ktor.output.convertInternalToOpenSpec
import io.github.tabilzad.ktor.writeFreshTo
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.cli.jvm.config.jvmClasspathRoots
import org.jetbrains.kotlin.config.CommonConfigurationKeys
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.impl.IrBlockImpl
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.fqNameWhenAvailable
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.ir.visitors.transformChildrenVoid
import java.io.File
import java.util.zip.ZipFile

/**
 * IR generation extension that performs three tasks:
 *
 * 1. **Write OpenAPI Specification**: Consumes all route/schema data collected during the FIR phase
 *    (by [SwaggerDeclarationChecker]) and writes it to a single OpenAPI spec file. This ensures
 *    all @GenerateOpenApi functions are processed before writing, and the output is fresh
 *    (no merge with stale data from previous compilations).
 *
 * 2. **Multi-module support**:
 *    - For contributor modules: writes a partial spec to META-INF/inspektor/openapi-partial.json
 *    - For aggregator modules: discovers partial specs on the compile classpath (JARs and class
 *      directories) plus any explicitly configured paths, and merges them with local routes
 *
 * 3. **Lower responds<T>() calls**: Removes calls to `responds<T>()` and `respondsNothing()`
 *    from the generated bytecode. These calls are only used for compile-time metadata extraction
 *    and should not incur any runtime overhead.
 *
 * This extension runs once per module, AFTER all FIR analysis is complete, making it the
 * ideal place to aggregate and write the collected OpenAPI data.
 */
internal class OpenApiIrGenerationExtension(
    private val configuration: CompilerConfiguration,
    private val config: PluginConfiguration
) : IrGenerationExtension {

    @OptIn(UnsafeDuringIrConstructionAPI::class)
    override fun generate(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        // 1. Write OpenAPI spec from collected data
        if (config.isEnabled) {
            writeOpenApiSpec()
        }

        // 2. Lower responds<T>() calls to no-ops
        lowerRespondsCalls(moduleFragment, pluginContext)
    }

    /**
     * Consumes all collected route/schema data and writes the OpenAPI specification.
     * This is called once per module, after all FIR analysis is complete.
     *
     * Behavior depends on module configuration:
     * - Contributor module: writes partial spec to resources for aggregation
     * - Aggregator module: merges partial specs from dependencies with local routes
     * - Standalone module: writes full spec directly (default behavior)
     */
    private fun writeOpenApiSpec() {
        val collected = OpenApiSpecCollector.consumeAll(configuration, config.filePath)

        // Merge all routes from different @GenerateOpenApi functions in this module
        val allRoutes = collected.flatMap { it.routes }

        // Merge all schemas, later entries override earlier ones with same key
        val allSchemas = collected
            .flatMap { it.schemas.entries }
            .associate { it.key to it.value }

        // Convert to OpenAPI spec
        val localSpec = if (allRoutes.isNotEmpty() || allSchemas.isNotEmpty()) {
            convertInternalToOpenSpec(
                routes = allRoutes,
                configuration = config,
                schemas = allSchemas
            )
        } else {
            null
        }

        when {
            // Contributor module: write partial spec to resources
            config.isContributor -> {
                val moduleId = config.moduleId
                if (localSpec != null && moduleId != null) {
                    writePartialSpec(localSpec, moduleId)
                }
            }

            // Aggregator module: merge partial specs from dependencies with local routes
            config.isAggregator -> {
                val partialSpecs = loadPartialSpecs()
                val mergedSpec = PartialSpecs.merge(partialSpecs, localSpec, ::warn)
                mergedSpec.writeFreshTo(config)
            }

            // Standalone module: write full spec directly
            else -> {
                localSpec?.writeFreshTo(config)
            }
        }
    }

    private val messageCollector: MessageCollector
        get() = configuration.get(CommonConfigurationKeys.MESSAGE_COLLECTOR_KEY, MessageCollector.NONE)

    private fun warn(message: String) =
        messageCollector.report(CompilerMessageSeverity.WARNING, "[inspektor] $message")

    /**
     * Writes a partial OpenAPI spec to the resources directory for multi-module aggregation.
     * The partial spec will be embedded in the JAR and discovered by aggregator modules.
     */
    private fun writePartialSpec(spec: OpenApiSpec, moduleId: String) {
        val resourcesPath = config.resourcesPath ?: return

        val outputDir = File(resourcesPath, PartialSpecLocation.RESOURCE_PATH)
        outputDir.mkdirs()

        File(outputDir, PartialSpecLocation.FILE_NAME).writeText(PartialSpecs.encode(spec, moduleId))
    }

    /**
     * Loads contributor partial specs from explicitly configured paths first, then from
     * `META-INF/inspektor/openapi-partial.json` entries discovered on the compile classpath
     * (both class directories and JARs, so published dependencies contribute too). When the
     * same module is found through both channels the explicitly configured path wins.
     */
    private fun loadPartialSpecs(): List<PartialOpenApiSpec> {
        val explicit = config.partialSpecPaths.mapNotNull { readPartialFile(File(it)) }
        val discovered = discoverPartialSpecsOnClasspath()

        val seenModules = mutableSetOf<String>()
        return (explicit + discovered)
            .filter { seenModules.add(it.moduleId) }
            .onEach { partial ->
                if (partial.version > PartialOpenApiSpec.CURRENT_VERSION) {
                    warn(
                        "Partial spec of module '${partial.moduleId}' has format version " +
                            "${partial.version}, newer than this plugin supports " +
                            "(${PartialOpenApiSpec.CURRENT_VERSION}). It was generated by a newer " +
                            "inspektor version; consider upgrading the aggregator's plugin."
                    )
                }
            }
    }

    private fun discoverPartialSpecsOnClasspath(): List<PartialOpenApiSpec> =
        configuration.jvmClasspathRoots.mapNotNull { root ->
            when {
                root.isDirectory -> readPartialFile(File(root, PartialSpecLocation.FULL_PATH))
                root.isFile && root.extension.equals("jar", ignoreCase = true) -> readPartialFromJar(root)
                else -> null
            }
        }

    private fun readPartialFile(file: File): PartialOpenApiSpec? {
        if (!file.isFile) return null
        return try {
            PartialSpecs.decode(file.readText())
        } catch (e: Exception) {
            warn("Failed to read partial spec from ${file.path}: ${e.message}")
            null
        }
    }

    private fun readPartialFromJar(jar: File): PartialOpenApiSpec? = try {
        ZipFile(jar).use { zip ->
            val entry = zip.getEntry(PartialSpecLocation.FULL_PATH) ?: return@use null
            val content = zip.getInputStream(entry).bufferedReader().use { reader -> reader.readText() }
            PartialSpecs.decode(content)
        }
    } catch (e: Exception) {
        warn("Failed to read partial spec from ${jar.path}: ${e.message}")
        null
    }

    /**
     * Removes calls to responds<T>() and respondsNothing() from bytecode.
     * These are compile-time only constructs for OpenAPI metadata.
     */
    @OptIn(UnsafeDuringIrConstructionAPI::class)
    private fun lowerRespondsCalls(
        moduleFragment: IrModuleFragment,
        pluginContext: IrPluginContext
    ) {
        moduleFragment.transformChildrenVoid(
            object : IrElementTransformerVoid() {
                override fun visitCall(expression: IrCall): IrExpression {
                    val call = super.visitCall(expression) as IrCall
                    val fqName = call.symbol.owner.fqNameWhenAvailable

                    // Replace responds<T>() and respondsNothing() with empty blocks
                    if (fqName == ClassIds.KTOR_RESPONDS_NO_OP ||
                        fqName == ClassIds.KTOR_RESPONDS_NOTHING_NO_OP
                    ) {
                        return IrBlockImpl(
                            call.startOffset,
                            call.endOffset,
                            pluginContext.irBuiltIns.unitType,
                            null,
                            emptyList()
                        )
                    }
                    return call
                }
            }
        )
    }
}
