[versions]
kotlinVersion = "2.1.20"
classgraph = "4.8.157"
jacksonVersion = "2.15.2"
ktorVersion = "2.2.4"
compilerTestingVersion = "0.5.0-alpha08"
assertJVerison = "3.24.2"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlinVersion" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }


[bundles]
jackson = ["jacksonKotlin", "jacksonYaml"]
ktor = ["ktor", "ktorNetty"]
kotlinGradle = ["kotlinGradleApi","kotlinGradle"]

[libraries]
kotlinCompiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlinVersion" }
assertJ = {module = "org.assertj:assertj-core", version.ref = "assertJVerison"}
classGraph = {module="io.github.classgraph:classgraph", version.ref="classgraph"}
junit = {module = "org.junit:junit-bom", version = "5.10.0"}
junitJupiter = {module = "org.junit.jupiter:junit-jupiter"}
compilerTest = {module = "dev.zacsweers.kctfork:core", version.ref = "compilerTestingVersion"}
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonVersion" }
jacksonYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jacksonVersion" }
ktor = { module = "io.ktor:ktor", version.ref = "ktorVersion" }
ktorNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorVersion" }
kotlinGradleApi = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlinVersion"}
kotlinGradle = {module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion"}
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }


