package io.github.tabilzad.ktor.model

import kotlinx.serialization.Serializable

/**
 * Represents a partial OpenAPI specification generated by a single module.
 * This is used for multi-module support where each module generates its own
 * partial spec, which is then aggregated by the main server module.
 *
 * The partial spec is stored as a resource file in:
 * META-INF/inspektor/openapi-partial.json
 */
@Serializable
data class PartialOpenApiSpec(
    /**
     * Unique identifier for the module that generated this spec.
     * Typically the Gradle module path (e.g., ":feature-users")
     */
    val moduleId: String,

    /**
     * OpenAPI version
     */
    val openapi: String = "3.1.0",

    /**
     * Paths defined in this module.
     * Map of path -> method -> operation details
     */
    val paths: Map<String, Map<String, PartialPath>> = emptyMap(),

    /**
     * Component schemas defined in this module.
     * These are the data types used in request/response bodies.
     */
    val schemas: Map<String, PartialTypeDescriptor> = emptyMap(),

    /**
     * Security schemes defined in this module (if any).
     */
    val securitySchemes: Map<String, SecurityScheme> = emptyMap()
)

/**
 * Partial path/operation definition for multi-module support.
 */
@Serializable
data class PartialPath(
    val summary: String? = null,
    val description: String? = null,
    val operationId: String? = null,
    val tags: List<String>? = null,
    val responses: Map<String, PartialResponse>? = null,
    val parameters: List<PartialParameter>? = null,
    val requestBody: PartialRequestBody? = null,
    val security: List<Map<String, List<String>>>? = null,
    val deprecated: Boolean? = null
)

@Serializable
data class PartialResponse(
    val description: String,
    val content: Map<String, Map<String, PartialTypeDescriptor>>? = null
)

@Serializable
data class PartialParameter(
    val name: String,
    val `in`: String,
    val required: Boolean = true,
    val description: String? = null,
    val schema: PartialTypeDescriptor? = null
)

@Serializable
data class PartialRequestBody(
    val required: Boolean = true,
    val content: Map<String, Map<String, PartialTypeDescriptor>>? = null
)

/**
 * Partial type descriptor for schemas.
 * This is a simplified version that can be serialized/deserialized across modules.
 */
@Serializable
data class PartialTypeDescriptor(
    val type: String? = null,
    val properties: Map<String, PartialTypeDescriptor>? = null,
    val items: PartialTypeDescriptor? = null,
    val enum: List<String>? = null,
    val fqName: String? = null,
    val description: String? = null,
    val ref: String? = null,
    val additionalProperties: PartialTypeDescriptor? = null,
    val oneOf: List<PartialTypeDescriptor>? = null,
    val required: List<String>? = null,
    val format: String? = null,
    val discriminator: PartialDiscriminator? = null
)

@Serializable
data class PartialDiscriminator(
    val propertyName: String = "type",
    val mapping: Map<String, String> = emptyMap()
)

/**
 * Location where partial specs are stored in module resources.
 */
object PartialSpecLocation {
    const val RESOURCE_PATH = "META-INF/inspektor"
    const val FILE_NAME = "openapi-partial.json"
    const val FULL_PATH = "$RESOURCE_PATH/$FILE_NAME"
}
